# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.app:
        build:
            context: ./docker
            dockerfile: Dockerfile
        image: laravel/app
        ports:
            - '8000:8000'
        volumes:
            - '.:/var/www/html/storage/app/public'
